# version: '3.8'

# services:
#   api:
#     build: ./api-service
#     ports:
#       - "3000:3000"
#     environment:
#       - DB_HOST=db
#       - DB_PORT=3306
#       - DB_USERNAME=user
#       - DB_PASSWORD=pass
#       - DB_NAME=vehicles
#       - REDIS_URL=redis://redis:6379
#     depends_on:
#       - db
#       - redis
#     volumes:
#       - ./api-service:/usr/src/app
#     restart: always

#   batch:
#     build: ./batch-job-service
#     environment:
#       - REDIS_URL=redis://redis:6379
#     depends_on:
#       - redis
#     volumes:
#       - ./batch-job-service:/usr/src/app
#     restart: always

#   frontend:
#     build: ./ui-service
#     ports:
#       - "3001:3000"
#     volumes:
#       - ./ui-service:/usr/src/app
#     stdin_open: true
#     tty: true
#     restart: always

#   db:
#     image: mysql:8
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: vehicles
#       MYSQL_USER: root
#       MYSQL_PASSWORD: 1234
#     ports:
#       - "3306:3306"
#     volumes:
#       - db_data:/var/lib/mysql

#   redis:
#     image: redis:7
#     ports:
#       - "6379:6379"
#     restart: always

# volumes:
#   db_data:
