version: "3.9"

services:
  # Redis Service
  redis:
    image: redis:5.0
    restart: always
    container_name: redis-server
    ports:
      - "6380:6380"  # Host:Container
    command: ["redis-server", "--port", "6380"]

  # MySQL Database
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: vehicledatadb
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # API Service
  api-service:
    build: ./api-service
    container_name: api-service
    depends_on:
      - redis
      - mysql
    ports:
      - "4000:4000"
    environment:
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6380
      - DB_HOST=localhost
    env_file:
      - ./api-service/.env
    volumes:
      - ./api-service:/app

  # Batch Job Worker
  batch-job-service:
    build: ./batch-job-service
    container_name: batch-job-service
    depends_on:
      - redis
      - mysql
    environment:
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6380
      - DB_HOST=localhost
    env_file:
      - ./batch-job-service/.env
    volumes:
      - ./batch-job-service:/app

  # Database Management Service
  database-service:
    build: ./database-service
    container_name: database-service
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
    volumes:
      - ./database-service:/app

  # React Frontend (Vite Build + Nginx Serve)
  ui-service:
    build: ./ui-service
    container_name: ui-service
    ports:
      - "5173:80"
    volumes:
      - ./ui-service:/app

volumes:
  mysql_data:
