version: "3.9"

services:
  redis:
    image: redis:5.0
    restart: always
    container_name: redis-server
    ports:
      - "6380:6380"
    command: ["redis-server", "--port", "6380"]

  mysql:
    image: mysql:8.0
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: vehicledatadb
      
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api-service:
    build: ./api-service
    container_name: api-service
    depends_on:
      - redis
      - mysql
    ports:
      - "4000:4000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6380
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 1234
      DB_DATABASE: vehicledatadb
      IMPORT_DIRECTORY: ./uploads/imports
      EXPORT_DIRECTORY: ./uploads/exports
    volumes:
      - ./api-service:/app

  batch-job-service:
    build: ./batch-job-service
    container_name: batch-job-service
    depends_on:
      - redis
      - mysql
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6380
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 1234
      DB_DATABASE: vehicledatadb
      IMPORT_DIRECTORY: ./uploads/imports
      EXPORT_DIRECTORY: ./uploads/exports
    volumes:
      - ./batch-job-service:/app

  database-service:
    build: ./database-service
    container_name: database-service
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 1234
      DB_DATABASE: vehicledatadb
    volumes:
      - ./database-service:/app

  ui-service:
    build: ./ui-service
    container_name: ui-service
    ports:
      - "5173:80"
    depends_on:
      - api-service
    volumes:
      - ./ui-service:/app

volumes:
  mysql_data:
