# api-service/Dockerfile

# Use Node.js official image as the base image
FROM node:16-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all files from the local `src` directory to the container
COPY ./src ./src

# Expose the port the app will run on
EXPOSE 3000

# Start the Express server
CMD ["npm", "start"]
